### ISSUE TITLE
How to exclude a directory of files?

### ISSUE THREAD

**Issue by shadowhand** [epriestley/arclint-examples#1]
I tried to do this for all our 3rd-party JS files, but it gives me an error:

``` js
"exclude": "lib\\/.*\\.js$"
```

> Regular expression "lib\/.*.js$" (in "exclude" configuration for linter "jshint") is not a valid regular expression.

**Comment by epriestley** [comment]
See IRC, but this needs an entire regexp including markers and flags, so try one of these:

```
"exclude": "(lib\\/.*\\.js$)"
"exclude": "@lib\\/.*\\.js$@"
```

..etc. The examples use `(` and `)` as markers because `/` is common in paths.

**Comment by shadowhand** [comment]
Thanks, this worked:

``` js
 "exclude" : "@/libs/.*\\.js$@"
```
